name: qwise
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #B
  bottom_bar_matu: ^1.3.0
  bard_api: ^1.0.0

  #C
  cupertino_icons: ^1.0.5
  cloud_firestore: ^4.7.1
  carousel_animations: ^0.0.4
  # cloud_firestore_odm: ^1.0.0-dev.59

  #F
  firebase_app_check: ^0.1.4+1
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  firebase_analytics: ^10.4.1
  firebase_crashlytics: ^3.3.1
  flutter_screenutil: ^5.8.2
  flutter_rating_bar: ^4.0.1
  flutter_easyloading: ^3.0.5
  firebase_storage: ^11.2.1
  flutter_local_notifications: ^14.1.0

  #G
  google_sign_in: ^6.1.2
  google_fonts: ^4.0.4 # http 1.0.0 in 4.0.5 which is not compatible with pod_player
  go_router: ^7.1.1
  # google_mobile_ads: ^3.0.0

  #L
  linkedin_login: ^2.2.1

  #I
  image_picker_pro: ^0.0.1+1
  in_app_update: ^4.0.1

  #M
  material_design_icons_flutter: ^6.0.7096

  #P
  permission_handler: ^10.2.0
  provider: ^6.0.5
  pin_code_fields: ^7.4.0
  pod_player: ^0.1.4

  #R
  random_avatar: ^0.0.8

  #S
  shared_preferences: ^2.1.1

  #T
  timeago: ^3.4.0

  #Y
  youtube_explode_dart: ^1.12.4
  dio: ^5.1.2
  flutter_native_splash: ^2.3.0
  firebase_messaging: ^14.6.1
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^2.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/qwise.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/
  #   - images/a_dot_ham.jpeg
