// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_bsLt6Cx_gvLqWzlPa9xV6CBqooU6ZTk',
    appId: '1:486735345213:web:b604307481d7213b401c54',
    messagingSenderId: '486735345213',
    projectId: 'qwise-learning',
    authDomain: 'qwise-learning.firebaseapp.com',
    storageBucket: 'qwise-learning.appspot.com',
    measurementId: 'G-HQYMSXWJ2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC6VGb8fGcLfWP-aqZj7WhHwuC-lKKMrs',
    appId: '1:486735345213:android:a84a7f854ecd8f14401c54',
    messagingSenderId: '486735345213',
    projectId: 'qwise-learning',
    storageBucket: 'qwise-learning.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH5Ju1Eco5JY3Jc_jgpAXsSOlChh7fzYM',
    appId: '1:486735345213:ios:31632988994f8fc4401c54',
    messagingSenderId: '486735345213',
    projectId: 'qwise-learning',
    storageBucket: 'qwise-learning.appspot.com',
    iosClientId: '486735345213-3qrkp5oddmdttg2dphlulkk6cki881qp.apps.googleusercontent.com',
    iosBundleId: 'com.example.qwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH5Ju1Eco5JY3Jc_jgpAXsSOlChh7fzYM',
    appId: '1:486735345213:ios:31632988994f8fc4401c54',
    messagingSenderId: '486735345213',
    projectId: 'qwise-learning',
    storageBucket: 'qwise-learning.appspot.com',
    iosClientId: '486735345213-3qrkp5oddmdttg2dphlulkk6cki881qp.apps.googleusercontent.com',
    iosBundleId: 'com.example.qwise',
  );
}
